[build]
  command = """
    # 1. Clean up previous Flutter SDK directory
    rm -rf flutter && \
    # 2. Clone the Flutter SDK
    git clone https://github.com/flutter/flutter.git && \
    # 3. Enable web support
    ./flutter/bin/flutter config --enable-web && \
    # 4. Get dependencies
    ./flutter/bin/flutter pub get && \
    # 5. Run the actual build with compile-time variables
    ./flutter/bin/flutter build web --release \
      --dart-define=SUPABASE_URL=${SUPABASE_URL} \
      --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY} \
      --dart-define=GOOGLE_SIGN_IN_WEB_CLIENT_ID=${GOOGLE_SIGN_IN_WEB_CLIENT_ID}
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200