# Corrected netlify.toml for Flutter Web

[build]
  # This new command installs Flutter first, then builds the app.
  command = "git clone https://github.com/flutter/flutter.git && ./flutter/bin/flutter config --enable-web && ./flutter/bin/flutter build web --release"
  
  functions = "netlify/functions"
  publish = "build/web"

## RECOMMENDED: This redirect is essential for Single Page Applications like Flutter.
## It makes sure that refreshing a page or going directly to a link like "your-site.com/about" works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200