name: Mirror to New Account

on:
  push:
    branches:
      - main  

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to new repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          source_repo: 'git@github.com:viraj0112/JEWELRY-NAFISA.git'
          destination_repo: 'https://dagina6999-crypto:${{ secrets.DESTINATION_REPO_TOKEN }}@github.com/dagina6999-crypto/JEWELRY-NAFISA.git'
          git_push_options: '--force --tags' 
